# Generated by Django 3.0.3 on 2020-07-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200729_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
